version: '2'
services:
  eureka:
#    environment:
#      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
#    image: sqshq/piggymetrics-registry
    build: eureka
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  server:
    build: server
    links:
      - eureka
